try:
    int("3.5")
finally:
    print("ValueError")
